services:
  spring-backend:
    build:
      context: . #El backend está en esta misma carpeta raíz
    container_name: spring-backend
    ports:
      - "8080:8080"
    restart: unless-stopped

  react-frontend:
    build:
      context: ./todo-frontend # Aquí entra a la subcarpeta para el front
    container_name: react-frontend
    ports:
      - "5174:80" # Mapeado al puerto 80 del contenedor al 5174 del host
    depends_on:
      - spring-backend
    restart: unless-stopped