# --- CONFIGURACIÓN DE TOMCAT (Servidor Web) ---
server.tomcat.threads.max=250
server.tomcat.accept-count=500

# --- CONFIGURACIÓN DE BASE DE DATOS (HikariCP) ---
spring.datasource.hikari.maximum-pool-size=50
spring.datasource.hikari.connection-timeout=10000